name: CI

on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build-and-deploy
        run: |
          remote_addr=`git remote get-url --push origin`
          commit_info=`git describe --all --always --long`
          user_name=`git log -1 --pretty=format:'%an'`
          user_emain=`git log -1 --pretty=format:'%ae'`
          deploy_branch=gh-pages
          dist_path=dist
          npm install -g pnpm@8.6.6
          pnpm install --frozen-lockfile
          pnpm build
          cd $dist_path
          git config --global init.defaultBranch $deploy_branch
          git init
          git config --global user.name "shenshi"
          git config --global user.email "shenshi@shouqianba.com"
          git add -A
          git commit -m "auto deploy"

          git remote add origin https://${{secrets.GITHUB_TOKEN}}:x-oauth-basic@github.com/shenshi/docker-slidev.git
          git push origin HEAD:$deploy_branch --force

